@startuml
' 作成日:2020/05/17 waim

title 簡易シミュレーションゲームの\nオブジェクト図

object プレイヤー{
 name
 学年
 持ち物
 性格美人度
 女子力度
 モテ度
 行動力
}

object NPC {
 name
 キャラビジュアル
 身分
 学年
 紹介文
 攻略可否
 攻略難易度
 主人公への好感度
}

legend
学園もの。
プレイヤーと仲間かどうかは好感度で判断する。
1週ゲームクリアしないと取り外せない持ち物有り。
end legend
@enduml
